name: Docker Image CI for GHCR

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      run: docker login --username ghoshritesh12 --password ${{ secrets.GHCR_ACCESS_TOKEN }} ghcr.io

    - name: Build the docker image
      run: docker build -t ghcr.io/ghoshritesh12/imgallery-backend:1.0.0 .

    - name: Push built image to GitHub Container Registry
      run: docker push ghcr.io/ghoshritesh12/imgallery-backend:1.0.0
