name: Docker Image CI for GHCR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      run: |
        docker login --username ghoshritesh12 --password ${{ secrets.GHCR_ACCESS_TOKEN }} ghcr.io
        docker build -t ghcr.io/ghoshritesh12/imgallery-backend:latest .
        docker push ghcr.io/ghoshritesh12/imgallery-backend:latest
